kind: Service
apiVersion: v1
metadata:
  name: node-exporter-external
  labels:
    app: node-exporter-external
    monitoring: enabled
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
  selector:
    app: node-exporter-external